import type { Result } from "../../../../../../core/helpers/ResultC";
import type { InstallmentGateway } from "../../../infraestructure/DebtGatweay";
import type { CollectionAttemptGateway } from "../../../infraestructure/CollectionAttemptGateway";
import type { CollectionAttempt } from "../../entities/CollectionAttempt";
import { ok, fail } from "../../../../../../core/helpers/ResultC";
import type { DebtGateway } from "../../../infraestructure/DebtGatweay";

export interface CreateCollectionAttemptUseCaseInput {
    companyId: string;
    description: string;
    collectorId: string;
    installmentId: string;
    location?: import("../../entities/Payment").GeoLocation;
}

export type CreateCollectionAttemptUseCaseError =
    | { code: "UNKNOWN_ERROR" }
    | { code: "INSTALLMENT_NOT_FOUND" };

export class CreateCollectionAttemptUseCase {
    private attemptGateway: CollectionAttemptGateway;
    private installmentGateway: InstallmentGateway;
    private debtGateway: DebtGateway;

    constructor(
        attemptGateway: CollectionAttemptGateway,
        installmentGateway: InstallmentGateway,
        debtGateway: DebtGateway
    ) {
        this.attemptGateway = attemptGateway;
        this.installmentGateway = installmentGateway;
        this.debtGateway = debtGateway;
    }

    async execute(input: CreateCollectionAttemptUseCaseInput): Promise<Result<null, CreateCollectionAttemptUseCaseError>> {
        const { companyId, installmentId, collectorId, description, location } = input;

        // 1. Get Installment to verify existence and get current state
        const instResult = await this.installmentGateway.getById({
            companyId,
            installmentId,
            collectorId
        });

        if (!instResult.ok) {
            return fail({ code: "INSTALLMENT_NOT_FOUND" });
        }

        const installment = instResult.value.state;
        const date = new Date().toISOString();

        // Fetch Debt to get its name
        const debtResult = await this.debtGateway.getById({
            companyId,
            idDebt: installment.debtId
        });

        const debtName = debtResult.state.ok ? debtResult.state.value?.name : "Deuda";

        // 2. Create CollectionAttempt record
        const attempt: CollectionAttempt = {
            id: "", // Generated by repo
            companyId,
            installmentId,
            debtId: installment.debtId,
            customerId: installment.costumerId,
            collectorId,
            colletorDescription: description,
            date,
            location,
            name: `${debtName} ${installment.installmentNumber}`
        };

        const attemptResult = await this.attemptGateway.create({
            companyId,
            attempt
        });

        if (!attemptResult.ok) {
            return fail({ code: "UNKNOWN_ERROR" });
        }

        // 3. Update Installment summary fields
        const updatedInstallment = {
            ...installment,
            attemptedCollection: true,
            dateAttemptedPayment: date.split("T")[0],
            descriptionAttemptedPayment: description,
            locationAttemptedPayment: location
        };

        const updateResult = await this.installmentGateway.updateById({
            companyId,
            installment: updatedInstallment
        });

        if (!updateResult.ok) {
            return fail({ code: "UNKNOWN_ERROR" });
        }

        return ok(null);
    }
}
